export const couponList = [
  {
    id: 1,
    couponcode: "ABC125",
    discount: "120",
    discounttype: "flat",
    uselimit: "100",
    usecount: "20",
    startdate: "12/16/2025",
    expiredate: "01/01/2026",
    coupontype: "Category",
    brand: "",
    category: "man",
    subcategory: "",
  },
  {
    id: 2,
    couponcode: "BCD253",
    discount: "80",
    discounttype: "flat",
    uselimit: "50",
    usecount: "",
    startdate: "12/16/2025",
    expiredate: "01/01/2026",
    coupontype: "brand",
    brand: "XYZ",
    category: "",
    subcategory: "",
  },
  {
    id: 3,
    couponcode: "EFG7895",
    discount: "200",
    discounttype: "flat",
    uselimit: "40",
    usecount: "20",
    startdate: "12/16/2025",
    expiredate: "01/01/2026",
    coupontype: "subcategory",
    brand: "",
    category: "",
    subcategory: "shoes",
  },
  {
    id: 4,
    couponcode: "WVFS542",
    discount: "50",
    discounttype: "flat",
    uselimit: "400",
    usecount: "120",
    startdate: "12/16/2025",
    expiredate: "01/01/2026",
    coupontype: "category",
    brand: "",
    category: "woman",
    subcategory: "",
  },
  {
    id: 5,
    couponcode: "QAWE1425",
    discount: "40",
    discounttype: "flat",
    uselimit: "65",
    usecount: "",
    startdate: "12/16/2025",
    expiredate: "01/01/2026",
    coupontype: "brand",
    brand: "yellow",
    category: "",
    subcategory: "",
  },
];
