

export const OderList = [
  {
    id: 1,
    order_id: "ORD-12345",
    price: 600,
    couponCode: "ABCD123",
    couponDiscount: 50,
    shipping: 60,
    total: 610,
    Payment: "Online",
    status: "Processing",
    date: "2023-10-01",
    Status:"",
    product:{
        title: "Product A",
        quantity: 2,
        price: 300,
        color: "Red",
        size: "M",
    },
    customer: {
      name: "John Doe",
      email: "john@gmail.com",
      Phone: "01746770324",
      address: "Dhaka, Bangladesh,Mirpur-10",
    },
  },
  {
    id: 2,
    order_id: "ORD-12346",
    price: 700,
    couponCode: "ABCD123",
    couponDiscount: "",
    shipping: 60,
    total: 760,
    Payment: "Online",
    status: "Processing",
    date: "2023-10-01",
    Status:"",
    product:{
        title: "Product b",
        quantity: 4,
        price: 700,
        color: "green",
        size: "",
    },
    customer: {
      name: "Al Mamun",
      email: "mamon@gmail.com",
      Phone: "01746770325",
      address: "mirpur-10,Dhaka,Bangladesh",
    },
  },
  {
    id: 3,
    order_id: "ORD-12347",
    price: 800,
    couponCode: "ABCD128",
    couponDiscount: "",
    shipping: 120,
    total: 920,
    Payment: "COD",
    status: "concelled",
    date: "2023-10-01",
    Status:"",
    product:{
        title: "Product C",
        quantity: 1,
        price: 600,
        color: "",
        size: "l",
    },
    customer: {
      name: "Md.Rakibul Islam",
      email: "islam@gmail.com",
      Phone: "0197456287",
      address: "Brahmanbaria,Meddea-titaspara,Bangladesh",
    },
  },
  {
    id: 4,
    order_id: "ORD-123414",
    price: 600,
    couponCode: "ABCD145",
    couponDiscount: 50,
    shipping: 60,
    total: 610,
    Payment: "Online",
    status: "Processing",
    date: "2023-10-01",
    Status:"",
    product:{
        title: "Product A",
        quantity: 2,
        price: 300,
        color: "Red",
        size: "M",
    },
    customer: {
      name: "John Doe",
      email: "deo@gmail.com",
      Phone: "01845712587",
      address: "Cox's Bazar,Bangladesh,Mirpur-10",
    },
  },
  
];
