import shirt from "@/src/assets/product/tshirt.jpg";
import shirt2 from "@/src/assets/product/tshirt2.jpg";
import shirt3 from "@/src/assets/product/tshirt3.jpg";
import shirt4 from "@/src/assets/product/tshirt4.jpg";
import shirt5 from "@/src/assets/product/tshirt5.jpeg";
import shirt6 from "@/src/assets/product/tshirt6.jpg";
import shirt7 from "@/src/assets/product/tshirt7.jpg";
import shirt8 from "@/src/assets/product/tshirt8.jpeg";
import shirt9 from "@/src/assets/product/tshirt9.jpg";
import shirt10 from "@/src/assets/product/tshirt10.jpg";
import shirt11 from "@/src/assets/product/tshirt11.jpg";
import shirt12 from "@/src/assets/product/tshirt12.jpg";
import shirt13 from "@/src/assets/product/tshirt13.jpg";
import shirt14 from "@/src/assets/product/tshirt14.jpg";

export const productList = [
  {
    id: 1,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    images: [shirt, shirt2, shirt3, shirt4],
    availability: "In Stock",
    rating: 4.5,

    discountType: "flat",
    discount: 120,
    price: 3500,
    mrpPrice: 4201,
    inventoryType: "size",
    inventory: [
      {
        id: 200,
        color: "",
        level: "S",
        quantity: 12,
        soldquantity: 4,
        holdquantity: 2,
      },
      {
        id: 201,
        color: "",
        level: "M",
        quantity: 20,
        soldquantity: 8,
        holdquantity: 8,
      },
      
    ],
    category: "Handbags",
    subcategory: "watches",
    childcategory: "watches",
    frontview: shirt,
    backview: shirt2,
    label: "",

    code: "ZARGANZ123",
  },
  {
    id: 2,
    title: "Zara Women Leather Bag",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    availability: "In Stock",
    rating: 4.5,
    price: 500,
    mrpPrice: 600,
    discountType: "flat",
    inventoryType: "color",
    inventory: [
      {
        id: 400,
        color: "red",
        level: "",
        quantity: 12,
        soldquantity: 4,
        holdquantity: 2,
      },
      {
        id: 401,
        color: "green",
        level: "",
        quantity: 20,
        soldquantity: 8,
        holdquantity: 8,
      },
     
    ],
    discount: "110",
    category: "watches",
    subcategory: "watches",
    childcategory: "watches",
    label: "",
    code: "ZARGANZ2045",
    frontview: shirt2,
    backview: shirt3,
  },
  {
    id: 3,
    title: "Travel Leather Backpack",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "Out of Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    price: 350,
    mrpPrice: 400,
    discount: "80",
    discountType: "flat",
    inventoryType: "colorsize",
    inventory: [
      {
        id: 500,
        color: "red",
        level: "S",
        quantity: 12,
        soldquantity: 4,
        holdquantity: 2,
      },
    ],
    category: "Shoes",
    subcategory: "watches",
    childcategory: "watches",
    label: "",
    code: "WEBSE2045",
    frontview: shirt3,
    backview: shirt4,
  },
  {
    id: 4,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    price: 7580,
    mrpPrice: 8000,
    discount: 200,
    discountType: "flat",
    inventoryType: "colorsize",
    inventory: [
      {
        id: 500,
        color: "red",
        level: "S",
        quantity: 12,
        soldquantity: 4,
        holdquantity: 2,
      },
      {
        id: 501,
        color: "green",
        level: "M",
        quantity: 20,
        soldquantity: 8,
        holdquantity: 8,
      },
      {
        id: 502,
        color: "pink",
        level: "xl",
        quantity: 22,
        soldquantity: 8,
        holdquantity: 12,
      },
    ],
    category: "Perfume",
    subcategory: "watches",
    childcategory: "watches",
    frontview: shirt5,
    backview: shirt6,
    label: "",
    code: "TSSE2045",
  },
  {
    id: 5,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "Out of Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    price: 3500,
    mrpPrice: "",
    discount: "60",
    discountType: "flat",
    inventoryType: "size",
    inventory: [
      {
        id: 700,
        color: "",
        level: "S",
        quantity: 12,
        soldquantity: 4,
        holdquantity: 2,
      },
      {
        id: 701,
        color: "",
        level: "M",
        quantity: 20,
        soldquantity: 8,
        holdquantity: 8,
      },
    ],
    category: "Handbags",
    subcategory: "watches",
    childcategory: "watches",
    label: "box packaging",
    code: "YAAS2045",
    frontview: shirt6,
    backview: shirt7,
  },
  {
    id: 6,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "Out of Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    price: 1280,
    mrpPrice: "",
    category: "Perfume",
    subcategory: "watches",
    childcategory: "watches",
    discount: 80,
    discountType: "flat",
    inventoryType: "color",
    inventory: [
      {
        id: 800,
        color: "yellow",
        level: "",
        quantity: 12,
        soldquantity: 4,
        holdquantity: 2,
      },
    ],
    frontview: shirt7,
    backview: shirt8,
    label: "",
    code: "QEAS2045",
  },
  {
    id: 7,
    title: "iPhone 8 Plus 64GB Full Color",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    availability: "In Stock",
    rating: 4.5,
    price: 620,
    mrpPrice: 700,
    discount: 60,
    discountType: "flat",
    inventoryType: "",
    inventory: [
      {
        id: 900,
        color: "",
        level: "",
        quantity: 5,
        soldquantity: 1,
        holdquantity: 4,
      },
      {
        id: 901,
        color: "",
        level: "",
        quantity: 8,
        soldquantity: 0,
        holdquantity: 8,
      },
    ],
    category: "watches",
    subcategory: "watches",
    childcategory: "watches",
    label: "new arrival",
    code: "XXEAS2045",
    frontview: shirt8,
    backview: shirt9,
  },
  {
    id: 8,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    availability: "In Stock",
    rating: 4.5,
    discount: 120,
    discountType: "flat",
    inventoryType: "color",
    inventory: [
      {
        id: 900,
        color: "red",
        level: "",
        quantity: 12,
        soldquantity: 4,
        holdquantity: 2,
      },
    ],
    price: 3500,
    mrpPrice: 4201,
    category: "Handbags",
    subcategory: "watches",
    childcategory: "",
    frontview: shirt9,
    backview: shirt10,
    label: "",
    code: "ZARGANZ123",
  },

  {
    id: 9,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    availability: "In Stock",
    rating: 4.5,
    discount: 120,
    discountType: "flat",
    inventoryType: "color",
    inventory: [
      {
        id: 910,
        color: "yellow",
        level: "",
        quantity: 12,
        soldquantity: 4,
        holdquantity: 2,
      },
    ],
    price: 3500,
    mrpPrice: 4201,
    category: "Handbags",
    subcategory: "",
    childcategory: "watches",
    frontview: shirt10,
    backview: shirt11,
    label: "",
    code: "ZARGANZ123",
  },
  {
    id: 10,
    title: "Zara Women Leather Bag",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    availability: "In Stock",
    rating: 4.5,
    price: 500,
    mrpPrice: 600,
    discount: 120,
    discountType: "flat",
    inventoryType: "size",
    inventory: [
      {
        id: 950,
        color: "",
        level: "xl",
        quantity: 12,
        soldquantity: 4,
        holdquantity: 2,
      },
    ],
    category: "watches",
    subcategory: "",
    childcategory: "",
    label: "",
    code: "ZARGANZ2045",
    frontview: shirt11,
    backview: shirt12,
  },
  {
    id: 11,
    title: "Zara Women Leather Bag",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    availability: "In Stock",
    rating: 4.5,
    price: 500,
    mrpPrice: 600,
    discount: 120,
    discountType: "flat",
    inventoryType: "colorsize",
    inventory: [
      {
        id: 980,
        color: "red",
        level: "",
        quantity: 12,
        soldquantity: 4,
        holdquantity: 2,
      },
    ],
    category: "watches",
    subcategory: "watches",
    childcategory: "watches",
    label: "",
    code: "ZARGANZ2045",
    frontview: shirt12,
    backview: shirt13,
  },
  {
    id: 12,
    title: "Travel Leather Backpack",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "Out of Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    price: 350,
    mrpPrice: 400,
    discount: 120,
    discountType: "flat",
    inventoryType: "color",
    inventory: [
      {
        id: 900,
        color: "red",
        level: "",
        quantity: 200,
        soldquantity: 8,
        holdquantity: 192,
      },
    ],
    category: "Shoes",
    subcategory: "watches",
    childcategory: "watches",
    label: "",
    code: "WEBSE2045",
    frontview: shirt13,
    backview: shirt14,
  },
];
